### ISSUE TITLE
Sometimes "tmc <anything>" -command is not starting the server

### ISSUE THREAD

**Issue by wakr** [rage/tmc-cli#77] opened 2015-06-26 15:33 UTC
User has to run shutdown.sh -script to get it working again :open_mouth:

**Comment by UMTti** [comment] 2015-08-07 14:19
could not reproduce anymore

**Comment by zinkko** [comment] 2015-08-10 06:23
This is a duplicate of #93 which has been fixed.

**Closed by zinkko** 2015-08-10 06:23 UTC
Labels: bug, duplicate
