### ISSUE TITLE
Submit doesn't find tmc-testcourse's exercises

### ISSUE THREAD

**Issue by JaniL** [rage/tmc-cli#76] opened 2015-06-26 13:51 UTC
Right now `tmc submit`is unable to find tmc-testcourse's exercise 'trivial'.

![Imgur](http://i.imgur.com/pLBB9T0.png)

Submitting exercises from courses such as ohpe has no such problem:

![Imgur](http://i.imgur.com/fJ9NpXI.png)

**Comment by zinkko** [comment] 2015-07-31 06:55
Could not reproduce

**Comment by UMTti** [comment] 2015-08-11 08:10
could not reproduce also so I close this issue

**Closed** 2015-08-11 08:09 UTC
